"""add Users table

Revision ID: dfa8e2159abd
Revises: ecf1ea6ce68e
Create Date: 2023-03-10 12:07:32.914216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfa8e2159abd'
down_revision = 'ecf1ea6ce68e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
