"""add Users

Revision ID: ecf1ea6ce68e
Revises: 77a189f091f5
Create Date: 2023-03-10 11:57:25.331006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecf1ea6ce68e'
down_revision = '77a189f091f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
